aproviders:
  openai:
    display_name: 'OpenAI'
  anthropic:
    display_name: 'Anthropic'
  gemini:
    display_name: 'Gemini'

models:
  gpt-4o:
    provider: openai
    display_name: 'GPT-4o'
    credit_multiplier: 3
  gpt-4o-mini:
    provider: openai
    display_name: 'GPT-4o Mini'
    credit_multiplier: 1
  o1-mini:
    provider: openai
    display_name: 'o1 Mini'
    credit_multiplier: 1
  o1-preview:
    provider: openai
    display_name: 'o1 Preview'
    credit_multiplier: 2
  o3-mini:
    provider: openai
    display_name: 'o3 Mini'
    credit_multiplier: 1
  claude-3-5-haiku-latest:
    provider: anthropic
    display_name: 'Claude 3.5 Haiku'
    coming_soon: false
    credit_multiplier: 2
  claude-3-5-sonnet-latest:
    provider: anthropic
    display_name: 'Claude 3.5 Sonnet'
    coming_soon: false
    credit_multiplier: 3
  gemini-1.5-flash:
    provider: gemini
    display_name: 'Gemini 1.5 Flash'
    credit_multiplier: 1
  gemini-1.5-pro:
    provider: gemini
    display_name: 'Gemini 1.5 Pro'
    credit_multiplier: 3
  whisper-1:
    provider: openai
    display_name: 'Whisper'
    credit_multiplier: 1
  text-embedding-3-small:
    provider: openai
    display_name: 'Text Embedding 3 Small'
    credit_multiplier: 1

features:
  editor:
    models:
      [
        gpt-4o-mini,
        o1-mini,
        gpt-4o,
        claude-3-5-haiku-latest,
        gemini-1.5-flash,
        gemini-1.5-pro,
      ]
    default: gpt-4o-mini
  assistant:
    models:
      [
        gpt-4o-mini,
        o1-mini,
        gpt-4o,
        o3-mini,
        claude-3-5-haiku-latest,
        claude-3-5-sonnet-latest,
        gemini-1.5-flash,
        gemini-1.5-pro,
      ]
    default: gpt-4o
  copilot:
    models:
      [
        gpt-4o-mini,
        gpt-4o,
        o1-mini,
        o3-mini,
        claude-3-5-haiku-latest,
        claude-3-5-sonnet-latest,
        gemini-1.5-flash,
        gemini-1.5-pro,
      ]
    default: gpt-4o
  label_suggestion:
    models: [gpt-4o-mini, gpt-4o, gemini-1.5-flash, claude-3-5-haiku-latest]
    default: gpt-4o-mini
  audio_transcription:
    models: [whisper-1]
    default: whisper-1
  help_center_search:
    models: [text-embedding-3-small]
    default: text-embedding-3-small
